name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch latest version
        run: |
          latest_version=$(curl -s "https://pypi.org/pypi/webscrapbook/json" | jq .info.version -r)
          echo "Latest version: $latest_version"
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV
          echo $latest_version > .latest-version
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: VERSION=${{ env.LATEST_VERSION }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/webscrapbook:latest
            ghcr.io/${{ env.OWNER_LC }}/webscrapbook:${{ env.LATEST_VERSION }}
